---
    apiVersion: v1
    kind: Secret
    metadata:
      name: sssecccrrrettt
      namespace: default
      labels:
        app: postgresql
    data:
      POSTGRES_PASSWORD: cm9vdA== #  "root"
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: postgresql-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: default
  labels:
    app: postgresql
spec:
    serviceName: postgresql
    replicas: 1
    selector:
        matchLabels:
        app: postgresql
    template:
        metadata:
        labels:
            app: postgresql
        spec:
        containers:
        - name: postgresql
            image: postgres:17-alpine
            ports:
            - containerPort: 5432
            name: postgres
            env:
            - name: POSTGRES_USER
            value: "admin"
            - name: POSTGRES_PASSWORD
            valueFrom:
                secretKeyRef:
                name: sssecccrrrettt
                key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
            value: "db"
            - name: POSTGRES_HOST_AUTH_METHOD
            value: "trust"
            volumeMounts:
            - name: postgresql-data
            mountPath: /var/lib/postgresql/data
        volumes:
            - name: postgresql-data
            persistentVolumeClaim:
                claimName: postgresql-pvc
---
    apiVersion: v1
    kind: Service
    metadata:
      name: postgresql
      namespace: default
      labels:
        app: postgresql
    spec:
      type: NodePort
      selector:
        app: postgresql
      ports:
      - port: 5432
        targetPort: 5432
        protocol: TCP
        nodePort: 30432