apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
  namespace: default  # Replace with your namespace if needed
  labels:
    app: nextjs-app
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
      - name: nextjs-container
        image: dshapova/next-runner:latest  # Replace with your container image
        ports:
        - containerPort: 3000  # Default Next.js port
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  namespace: default  # Replace with your namespace if needed
  labels:
    app: nextjs-app
spec:
  type: NodePort  # Use LoadBalancer, NodePort, or ClusterIP depending on your needs
  selector:
    app: nextjs-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000  # Forward to the container's port
    nodePort: 30001